# Cassandra Cluster Database Docker Compose 
services:
  cassandra-node1-dc1:
    image: cassandra:5.0.2
    container_name: cassandra-node1-dc1
    # restart: on-failure
    environment:
      - CASSANDRA_CLUSTER_NAME=DistributedTransactionsCluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_SEEDS=cassandra-node1-dc1,cassandra-node2-dc1
      # - CASSANDRA_SEEDS=cassandra-node1-dc1
      - CASSANDRA_LISTEN_ADDRESS=cassandra-node1-dc1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node1-dc1
      - CASSANDRA_BROADCAST_RPC_ADDRESS=cassandra-node1-dc1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_COMMITLOG_SYNC=batch
      - CASSANDRA_COMMITLOG_SYNC_PERIOD_IN_MS=10000
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_INITIAL_TOKEN=0000000000000000
      - JVM_OPTS=-Dcassandra.schema_agreement_wait_seconds=360 -Dcassandra.partitioner=org.apache.cassandra.dht.Murmur3Partitioner -javaagent:/opt/jmx_prometheus_javaagent.jar=7075:/etc/cassandra/cassandra.yml
      
    ports:
      - "9042:9042"
      - "7075:7075" # Expose JMX metrics
    networks:
      - cassandra-network-dtc
    volumes:
      - cassandra-node1-dc1-data:/var/lib/cassandra
      - ./jmx_prometheus_javaagent-1.0.1.jar:/opt/jmx_prometheus_javaagent.jar
      - ./cassandra.yml:/etc/cassandra/cassandra.yml

  cassandra-node2-dc1:
    image: cassandra:5.0.2
    container_name: cassandra-node2-dc1
    environment:
      - CASSANDRA_CLUSTER_NAME=DistributedTransactionsCluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_SEEDS=cassandra-node1-dc1,cassandra-node2-dc1
      # - CASSANDRA_SEEDS=cassandra-node1-dc1
      - CASSANDRA_LISTEN_ADDRESS=cassandra-node2-dc1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node2-dc1
      - CASSANDRA_BROADCAST_RPC_ADDRESS=cassandra-node2-dc1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_COMMITLOG_SYNC=batch
      - CASSANDRA_COMMITLOG_SYNC_PERIOD_IN_MS=10000
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_INITIAL_TOKEN= 1
      - JVM_OPTS=-Dcassandra.schema_agreement_wait_seconds=360 -Dcassandra.partitioner=org.apache.cassandra.dht.Murmur3Partitioner -javaagent:/opt/jmx_prometheus_javaagent.jar=7071:/etc/cassandra/cassandra.yml
    ports:
      - "9043:9042"
      - "7071:7070"
    networks:
      - cassandra-network-dtc
    volumes:
      - cassandra-node2-dc1-data:/var/lib/cassandra
      - ./jmx_prometheus_javaagent-1.0.1.jar:/opt/jmx_prometheus_javaagent.jar
      - ./cassandra.yml:/etc/cassandra/cassandra.yml

  cassandra-node1-dc2:
    image: cassandra:5.0.2
    container_name: cassandra-node1-dc2
    environment:
      - CASSANDRA_CLUSTER_NAME=DistributedTransactionsCluster
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack1
      - CASSANDRA_SEEDS=cassandra-node1-dc1,cassandra-node1-dc2
      # - CASSANDRA_SEEDS=cassandra-node1-dc2
      - CASSANDRA_LISTEN_ADDRESS=cassandra-node1-dc2
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node1-dc2
      - CASSANDRA_BROADCAST_RPC_ADDRESS=cassandra-node1-dc2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_COMMITLOG_SYNC=batch
      - CASSANDRA_COMMITLOG_SYNC_PERIOD_IN_MS=10000
      - JVM_OPTS=-Dcassandra.schema_agreement_wait_seconds=360 -Dcassandra.partitioner=org.apache.cassandra.dht.Murmur3Partitioner -javaagent:/opt/jmx_prometheus_javaagent.jar=7072:/etc/cassandra/cassandra.yml
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_INITIAL_TOKEN= 2

    ports:
      - "9044:9042"
      - "7072:7070"
    networks:
      - cassandra-network-dtc
    volumes:
      - cassandra-node1-dc2-data:/var/lib/cassandra
      - ./jmx_prometheus_javaagent-1.0.1.jar:/opt/jmx_prometheus_javaagent.jar
      - ./cassandra.yml:/etc/cassandra/cassandra.yml
  node-exporter1:
    image: prom/node-exporter:latest
    container_name: node-exporter1
    depends_on:
      - cassandra-node1-dc1
    ports:
      - "9100:9100"
    networks:
      - cassandra-network-dtc
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($|/)"
  
  node-exporter2:
    image: prom/node-exporter:latest
    container_name: node-exporter2
    depends_on:
      - cassandra-node2-dc1
    ports:
      - "9101:9100"
    networks:
      - cassandra-network-dtc
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($|/)"
  
  node-exporter3:
    image: prom/node-exporter:latest
    container_name: node-exporter3
    depends_on:
      - cassandra-node1-dc2
    ports:
      - "9102:9100"
    networks:
      - cassandra-network-dtc
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($|/)"
  

networks:
  cassandra-network-dtc:

volumes:
  cassandra-node1-dc1-data:
  cassandra-node2-dc1-data:
  cassandra-node1-dc2-data: